### PR TITLE
docs(node): initial getting started doc for node

### PR DESCRIPTION
**Pull request by noelweichbrodt**
### PR Checklist

Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [X] I am requesting to **pull a topic/feature/bugfix branch** (right side). In other words, not _master_.
- [X] I have run `npm test` against my changes and tests pass.
- [X] I have added or edited necessary documentation, or no docs changes are needed.

### Description

Adds a minimal (copied from repo readme) getting-started doc for Node.

### CODE REVIEW

**Comment by timmywil** [comment]
Just a couple things. I think the image needs to be added here, and then it'd be good if the spokestack.io links were made relative.

**Comment by noelweichbrodt** [comment]
misunderstood as porting the hero over, so i did that anyways + fixed the actual image you were talking about

**Comment by noelweichbrodt** [comment]
weird, neither my spacemacs error checker nor the commit hook check is seeing those graphql dupes

**Comment by timmywil** [comment]
The commit hook is working fine for me, but the hook was broken for a bit. You may need to rebase and `npm install` to get the latest hook.

**Comment by timmywil** [comment]
A lot of this has actually changed now that we have the speech pipeline added to node. But, we can wait until it's out of beta to update this doc.

**Pull request merged**
