### PR TITLE
docs: updated iOS examples with new speak api; updated docs with api id/secret

### PR DESCRIPTION
**Pull request by noelweichbrodt**
Minor updates to existing docs.

### CODE REVIEW

**Review by timmywil — CHANGES_REQUESTED** [review]
Perhaps you didn't run yarn. It should have formatted on commit. To fix the formatting,

```sh
$ yarn
$ yarn format
```

And commit the changes.

**Comment by noelweichbrodt** [comment]
it's 2020 and I'm still out here typing `npm install`

**Comment by space-pope** [comment]
You'll need an update to `nav.json` too to add your new file, like I just had to do on mine.

**Review by timmywil — APPROVED** [review]

**Pull request merged**
