### PR TITLE
fix: reformat all docs links to avoid redirects; fix some 404s

### PR DESCRIPTION
**Pull request by timmywil**
### PR Checklist

Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [x] I am requesting to **pull a topic/feature/bugfix branch** (right side). In other words, not _master_.
- [x] I have run `npm test` against my changes and tests pass.
- [x] I have added or edited necessary documentation, or no docs changes are needed.

### Description

- Docs links used to ignore spaces and uppercase letters in the folder names and created some strange URLs. That was fixed a while ago, but the existing links still worked for back-compat. This PR finally moves existing links to their appropriate places.

This PR probably conflicts with #159. I'll update after that is merged.

### CODE REVIEW

**Comment by space-pope** [comment]
Should we go ahead and rename the folders themselves to remove confusion? i.e., `Concepts` -> `concepts`

**Comment by timmywil** [comment]
@space-pope I don't think so. That would look weird in the nav.

**Comment by timmywil** [comment]
Sorry, I should be more clear. The folder name is also the display name in the nav. The URL is constructed from it correctly now tho.

**Comment by space-pope** [comment]
Gotcha; makes sense. I assume we _could_ add logic to titlecase the folder names for display in the nav, but I get just leaving it alone too.

**Pull request merged**
