### PR TITLE
docs(design): getting started content edits

### PR DESCRIPTION
**Pull request by roppem9**
@pdtyreus one thing I was confused about: when explaining a multi-modal interface, you talk about text input. Did you mean text via voice?

@timmywil I noticed the user testing post I wrote isn't included on the beta site. Did I upload that doc wrong? Not sure how it got dropped... I can add a link to that article once the article becomes available

### CODE REVIEW

**Review by pdtyreus — CHANGES_REQUESTED** [review]
I think these changes make a lot of sense. Just to follow better markdown practices, please change the 1, 2, 3.. bullets back to 1, 1, 1...

**Review by pdtyreus — APPROVED** [review]

**Comment by timmywil** [comment]
If you mean "Test with real people", that recently got removed [here](https://github.com/spokestack/spokestack-website/commit/80fb9e7568d7aac7e6a521aa1ff360b533b31b92#diff-a4d65ba62ff6b4c2d968748764d4b2ce) in #41. Should we add it back?

**Review by timmywil — APPROVED** [review]

**Comment by roppem9** [comment]
Ah, I see now that it was removed. Maybe not - could repurpose into a blog article or 2 instead.

**Pull request merged**
