### PR TITLE
React Native doc fixes

### PR DESCRIPTION
**Pull request by noelweichbrodt**
Based on feedback, improvements to docs for React Native.

### CODE REVIEW

**Review by pdtyreus — COMMENTED** [review]
It looks to me like there are 2 versions of the RN cookbook and getting started. One under "React Native" and the other under "react-native". That doesn't seem right to me.

**Comment by pdtyreus** [comment]
Also when I created my RN project it made an ObjC version of AppDelegate instead of a Swift one. So my AppDelegate.m ended up looking like this after removing Flipper and adding AVAudioSession

```objc
#import "AppDelegate.h"
#import <AVFoundation/AVFoundation.h>

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{

  [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayAndRecord mode:AVAudioSessionModeDefault options:AVAudioSessionCategoryOptionDefaultToSpeaker  error:nil];
  [[AVAudioSession sharedInstance] setActive:YES error:nil];
  
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"MinecraftAlexaSkill"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end
```

**Comment by noelweichbrodt** [comment]
Good catch on the swift/objc `AppDelegate`, i just got confused when I meant to put the objc one in!

**Pull request merged**
