### PR TITLE
Android + TTS documentation

### PR DESCRIPTION
**Pull request by space-pope**
This fills out the initial version of the Android section and adds a short guide for TTS.

Note that `nav.json` isn't totally being honored (at least it wasn't for me)—I'm trying to have the welcome doc show up at the very top, and then have the iOS section above Android, but Android keeps showing up at the top when I run the site locally. I haven't found anything explicit that does this; it just looks like the sections are sorted based on their contents' dates, a frontmatter field that's been deprecated.

### CODE REVIEW

**Comment by timmywil** [comment]
The graphql query was indeed trying to sort by frontmatter date, but that field no longer exists so it was just sorting on `undefined`. So, it was a noop. There is a manual sort in the docs nav that sorts by `nav.json`. I'll see if I can figure out why it's not putting Welcome at the top.

**Comment by timmywil** [comment]
The problem was due to a mismatch between what's in nav.json and what is set for the `navId` (e.g. 'Android Speech Pipeline' vs 'Spokestack Android Speech Pipeline').

**Comment by timmywil** [comment]
I added a check that will throw an error for that case in the future.

**Comment by space-pope** [comment]
D'oh. Thanks—I was wondering why the sections that were in both the local and published versions weren't ordered the same.

**Pull request closed without merging**
