### PR TITLE
Changed blog + docs content max-width

### PR DESCRIPTION
**Pull request by roppem9**
### PR Checklist

Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [x] I am requesting to **pull a topic/feature/bugfix branch** (right side). In other words, not _master_.
- [x] I have run `npm test` against my changes and tests pass.
- [x] I have added or edited necessary documentation, or no docs changes are needed.

### Description

Included in this PR:
- Width is wider for blog + doc content after noticing that many sites (including Stripe) have different content widths for their docs and blog content
- Removed underline for links
- Fixed indentation on bulleted lists

### CODE REVIEW

**Comment by noelweichbrodt** [comment]
LGTM, congrats on a code change PR! I'll defer to Timmy for final approval.

**Comment by timmywil** [comment]
The width on the docs pages is too large for screen sizes between 980px and 1600px. What's the main goal here?

**Comment by noelweichbrodt** [comment]
we have code samples extend past the current max, plus on big screens the text body is rather skinny.

**Comment by roppem9** [comment]
Trying to make it so the code snippets aren't so cut off. I actually copied the width for docs from Stripe: https://stripe.com/docs

**Comment by timmywil** [comment]
Stripe does not have this problem. There's a difference between set width and max width.

**Comment by roppem9** [comment]
Well, yes - there's a reasonable chance I implemented it incorrectly. Point is, I'd like to copy stripe's width for blog + docs

**Comment by timmywil** [comment]
Looks like the max-width settings use an invalid unit "vm". I'll fix that.

**Pull request merged**
