### PR TITLE
docs(design): formatting issue in opening paragraph

### PR DESCRIPTION
**Pull request by roppem9**

### CODE REVIEW

**Comment by timmywil** [comment]
@roppem9 Please add any further changes to this PR. You can do that by pushing to the `roppem9-patch-1` branch.

**Comment by timmywil** [comment]
@roppem9 By the way, to do that on GitHub, first select your branch before going to the file you want to edit. 
image

**Comment by roppem9** [comment]
Sounds good - will do!

**Comment by timmywil** [comment]
@roppem9 Do you have further changes to add? If not, I'll go ahead and merge this.

**Comment by timmywil** [comment]
It seems these changes made it into develop another way.

**Pull request closed without merging**
