### PR TITLE
docs: so many video embeds

### PR DESCRIPTION
**Pull request by noelweichbrodt**
### PR Checklist

Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [X] I am requesting to **pull a topic/feature/bugfix branch** (right side). In other words, not _master_.
- [X] I have run `npm test` against my changes and tests pass.
- [X] I have added or edited necessary documentation, or no docs changes are needed.

### Description

Add video embeds using `iframe` to appropriate `/content` pages.

### CODE REVIEW

**Comment by noelweichbrodt** [comment]
@roppem9 using this PR, could you derive which videos should link to the pages that are embedding them and add those pages to the youtube video description?

**Review by timmywil — CHANGES_REQUESTED** [review]
We already have a plugin that makes embedding videos seemless and will work much better than a fixed iframe. See https://www.gatsbyjs.com/plugins/gatsby-remark-embed-video/?=video#usage for how to integrate videos.

**Comment by timmywil** [comment]
Note that the plugin supports a11y so please add titles for each one:

```
`youtube: [Cool Youtube Video](https://www.youtube.com/watch?v=2Xc9gXyf2G4)`
```

**Comment by noelweichbrodt** [comment]
Thanks @timmywil for the pointer, saw the `vimeo` directive in a couple places but couldn't figure out where it was coming from.

**Comment by roppem9** [comment]
@noelweichbrodt updated descriptions for the following youtube videos:

- Voice is just another interface: https://www.youtube.com/watch?v=wbJ8fZh-iQw
- Build your own voice interface (VUI): https://www.youtube.com/watch?v=AvhQ6-9nCrQ
- Wakewords for iOS apps: https://www.youtube.com/watch?v=3qKJMrkbZA8
- The basic elements of voice interfaces: https://www.youtube.com/watch?v=1x4MdTKEy3E

Do we need to do the same for Vimeo? I thought we were going to kill the Vimeo account due to the pay wall?

**Comment by noelweichbrodt** [comment]
@roppem9 youtube description updates are exactly what I wanted, ty. For vimeo, I think we should download all vimeo videos and reupload to youtube, then repeat this process for them.

**Comment by roppem9** [comment]
@noelweichbrodt ok, I can do that

**Comment by roppem9** [comment]
@noelweichbrodt In the process of moving all our videos from Vimeo -> YouTube. Only two videos we'll need to embed throughout the site:

- Spokestack Tray Demo on iOS: https://www.youtube.com/watch?v=0RBITe8RNco
- Spokestack Overview: https://www.youtube.com/watch?v=MW2cYSQhbZE

Do you want to go ahead and embed these videos in appropriate blog/docs pages, then I can update the descriptions with links on YouTube?

**Comment by roppem9** [comment]
@noelweichbrodt one more video for you:

- How Did We Get Here?: https://www.youtube.com/watch?v=B-TIVeN2Kho

**Comment by timmywil** [comment]
@noelweichbrodt Aside from the conflict, is this PR ready to go?

**Comment by noelweichbrodt** [comment]
I have some more to add, so I'll fix the conflicts and let you know when it's ready again.

**Comment by noelweichbrodt** [comment]
@roppem9 per earlier discussion, I've added embeds for the ex-vimeo videos. Can you update the descriptions with links on YouTube, please?

**Comment by roppem9** [comment]
@noelweichbrodt youtube cross-linking complete - I even made sure to include UTM parameters with all links in our youtube channel so we can better track which video a user came from to the site

**Pull request merged**
